# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 21:15
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'++', max_length=2)),
                ('deliverable', models.BooleanField(default=False)),
                ('product', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'((', max_length=50)),
                ('mail_code', models.CharField(default=b'', max_length=100)),
                ('height', models.IntegerField(default=1)),
                ('length', models.IntegerField(default=1)),
                ('width', models.IntegerField(default=1)),
                ('weight', models.IntegerField(default=10)),
                ('value', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Followed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.IntegerField(default=1)),
                ('follower', models.IntegerField(default=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'!#', max_length=50)),
                ('content', models.TextField(default=b'')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=50)),
                ('code', models.CharField(default=b'', max_length=100)),
                ('city', models.CharField(default=b'', max_length=100)),
                ('country', models.CharField(default=b'', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.IntegerField(default=0)),
                ('visual', models.CharField(default=b'', max_length=100)),
                ('career', models.CharField(default=b'', max_length=50)),
                ('birthday', models.DateTimeField(default=datetime.date(2017, 2, 27))),
                ('google_token', models.TextField(default=b'', max_length=120)),
                ('twitter_token', models.TextField(default=b'', max_length=120)),
                ('facebook_token', models.TextField(default=b'', max_length=120)),
                ('bio', models.TextField(default=b'', max_length=140)),
                ('interface', models.IntegerField(default=1)),
                ('typeditor', models.IntegerField(default=1)),
                ('monetize', models.IntegerField(default=0)),
                ('language', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sellable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'$$', max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('value', models.FloatField(default=1.0)),
                ('visual', models.CharField(default=b'', max_length=150)),
                ('sellid', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='deliverable',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='efforia.Sellable'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
