# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 19:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedly', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plethora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'!%', max_length=10)),
                ('description', models.CharField(default=b'', max_length=140)),
                ('link', models.CharField(default=b'', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=150)),
                ('category', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('token', models.CharField(max_length=20)),
                ('credit', models.IntegerField(default=0)),
                ('visual', models.CharField(default=b'', max_length=40)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sellable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feedly.Sellable')),
                ('category', models.IntegerField(default=1)),
                ('description', models.TextField()),
            ],
            bases=('feedly.sellable',),
        ),
        migrations.CreateModel(
            name='Spreadable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=50)),
                ('content', models.TextField()),
                ('spreaded', models.CharField(default=b'efforia', max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpreadBasket',
            fields=[
                ('basket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feedly.Basket')),
            ],
            bases=('feedly.basket',),
        ),
        migrations.CreateModel(
            name='Spreaded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'!!', max_length=10)),
                ('spread', models.IntegerField(default=1)),
                ('spreaded', models.IntegerField(default=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
