# Generated by Django 3.0.5 on 2020-05-08 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plethora', '0003_auto_20200424_2341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
